=== Mariinaaa/Wintertrack/lectura.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Lectura de Sensor",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "sensorId": {
            "type": "string"
        },
        "valor": {
            "type": "number"
        },
        "unidad": {
            "type": "string"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time"
        }
    },
    "required": [
        "id",
        "sensorId",
        "valor",
        "unidad",
        "timestamp"
    ]
}

=== Mariinaaa/Wintertrack/IoT/data/lecturas.json
[
    {
        "id": "LEC-AF-001",
        "sensorId": "REM-TS01",
        "valor": 150,
        "unidad": "personas",
        "timestamp": "2025-10-16T10:00:00Z"
    },
    {
        "id": "LEC-VIB-001",
        "sensorId": "REM-TC02",
        "valor": 0.5,
        "unidad": "mm/s",
        "timestamp": "2025-10-16T10:01:00Z"
    },
    {
        "id": "LEC-TEMP-001",
        "sensorId": "REM-TS01-TEMP",
        "valor": -2.5,
        "unidad": "Â°C",
        "timestamp": "2025-10-16T10:02:00Z"
    },
    {
        "id": "LEC-AF-002",
        "sensorId": "REM-TS01",
        "valor": 155,
        "unidad": "personas",
        "timestamp": "2025-10-16T10:05:00Z"
    }
]
