=== Mariinaaa/Wintertrack/schemas/sensor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Sensor (Remonte)",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "tipo": {
            "type": "string",
            "enum": [
                "temperatura",
                "vibracion",
                "aforo"
            ]
        },
        "ubicacionId": {
            "type": "string"
        },
        "estadoOperacional": {
            "type": "string",
            "enum": [
                "Operativo",
                "Mantenimiento",
                "Cerrado"
            ]
        }
    },
    "required": [
        "id",
        "tipo",
        "ubicacionId",
        "estadoOperacional"
    ]
}

=== Mariinaaa/Wintertrack/services/IoT/data/sensores.json
[
    {
        "id": "REM-TS01",
        "tipo": "aforo",
        "ubicacionId": "ZonaPrincipiantes",
        "estadoOperacional": "Operativo"
    },
    {
        "id": "REM-TC02",
        "tipo": "vibracion",
        "ubicacionId": "ZonaExpertos",
        "estadoOperacional": "Operativo"
    },
    {
        "id": "REM-TS01-TEMP",
        "tipo": "temperatura",
        "ubicacionId": "ZonaPrincipiantes",
        "estadoOperacional": "Operativo"
    }
]
